import json
from PIL import Image, ImageDraw, ImageFont

# Load scenes
with open("data/scenes.json", "r", encoding="utf-8") as f:
    data = json.load(f)

WIDTH = 1280
HEIGHT = 720

for scene in data["scenes"]:

    scene_no = scene["scene"]
    title = scene["slide_title"]
    bullets = scene["bullet_points"]

    # Background
    img = Image.new(
        "RGB",
        (WIDTH, HEIGHT),
        (15, 23, 42)
    )

    draw = ImageDraw.Draw(img)

    try:
        title_font = ImageFont.truetype(
            "arial.ttf",
            42
        )

        bullet_font = ImageFont.truetype(
            "arial.ttf",
            28
        )

        brand_font = ImageFont.truetype(
            "arial.ttf",
            20
        )

    except:
        title_font = ImageFont.load_default()
        bullet_font = ImageFont.load_default()
        brand_font = ImageFont.load_default()

    # Header line
    draw.rectangle(
        [(0, 0), (WIDTH, 8)],
        fill=(0, 200, 140)
    )

    # Academy Name
    draw.text(
        (60, 40),
        "Blazly Academy",
        fill=(0, 200, 140),
        font=brand_font
    )

    # Title
    draw.text(
        (60, 110),
        title,
        fill="white",
        font=title_font
    )

    # Bullets
    y = 220

    for bullet in bullets:
        draw.text(
            (80, y),
            f"• {bullet}",
            fill="white",
            font=bullet_font
        )

        y += 70

    # Footer line
    draw.line(
        [(60, 650), (1220, 650)],
        fill=(80, 80, 80),
        width=2
    )

    # Footer text
    draw.text(
        (60, 670),
        "Generated by AI Video Agent",
        fill=(180, 180, 180),
        font=brand_font
    )

    img.save(
        f"outputs/slides/slide_{scene_no}.png"
    )

    print(
        f"✅ slide_{scene_no}.png created"
    )

print("🎉 All slides generated")